import type { NextPage } from 'next'
import styles from '../ui/styles/Home.module.css'
import Head from 'next/head'
import useIndex from '../data/hooks/pages/useIndex.page'
import PostList from '../ui/components/PostList/PostList'

const Home: NextPage = () => {
  const { posts } = useIndex()
  return (
    <div>
      <Head>
        <title>TreinaBlog</title>
        <meta name='description' content='Generated by create-next-app'></meta>
        <link rel="icon" href="favicon.ico" />
      </Head>

      <main>
        <PostList posts={posts} />
      </main>
    </div>
  )
}

export default Home
